window.MEDEVIA_SHEET_CONFIG = {
  gvizUrl: "",
};

window.MEDEVIA_FALLBACK_DATA = [
  {
    "id": "MEV-001",
    "nombre": "Abrazoterapia",
    "otrosNombres": "Terapia del abrazo / Abrazo terapéutico / Terapia afectiva por contacto físico",
    "queEs": "Práctica que propone que los abrazos o el contacto físico afectivo tienen efectos terapéuticos sobre la salud emocional y física, como reducción del estrés o mejora del bienestar. Se basa en la idea de que el contacto humano genera beneficios psicológicos",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "No tiene"
  },
  {
    "id": "MEV-002",
    "nombre": "Acupuntura",
    "otrosNombres": "Medicina tradicional china / terapia con agujas / punción terapéutica",
    "queEs": "La acupuntura es una práctica originaria de la medicina tradicional china que consiste en insertar agujas muy finas en puntos específicos del cuerpo. Según la tradición, estos puntos se ubican sobre “canales energéticos” o meridianos por donde circula la energía vital (llamada Qi), y su estimulación busca restablecer el equilibrio del organismo.",
    "riesgos": "",
    "conclusiones": "3",
    "cantidadArticulos": "21,576",
    "cantidadRevisiones": "1623",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Acupuncture%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-003",
    "nombre": "Angeloterapia",
    "otrosNombres": "Sanación con ángeles / curación angelical / terapia angelical",
    "queEs": "Angeloterapia es una pseudoterapia espiritual que afirma que la comunicación con ángeles o seres espirituales puede proporcionar guía y sanación emocional, espiritual o física. Involucra invocaciones, meditaciones y cartas oráculo canalizadas por un terapeuta que supuestamente transmite mensajes angelicales.",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-004",
    "nombre": "Apiterapia",
    "otrosNombres": "Terapia con veneno de abeja / Terapia con productos apícolas",
    "queEs": "La apiterapia agrupa prácticas que usan productos de la abeja (veneno, miel, propóleo, jalea real, polen) con fines terapéuticos. Incluye desde aplicaciones tópicas hasta picaduras intencionales. La evidencia clínica es limitada, heterogénea y dependiente del producto; existen riesgos relevantes, especialmente con veneno.",
    "riesgos": "",
    "conclusiones": "2",
    "cantidadArticulos": "68",
    "cantidadRevisiones": "4",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=apitherapy+%5BTitle%5D&filter=pubt.systematicreview y otro enlace con bee venom: https://pubmed.ncbi.nlm.nih.gov/?term=bee+venom+therapy+%5BTitle%5D",
    "anioReciente": "2020"
  },
  {
    "id": "MEV-005",
    "nombre": "Sonoterapia",
    "otrosNombres": "Terapia de armónicos / Terapia de sonido / Baños de sonido",
    "queEs": "Práctica que utiliza sonidos, vibraciones o música (por ejemplo, cuencos, gongs o frecuencias específicas) con la intención de promover relajación, bienestar emocional o equilibrio corporal.",
    "riesgos": "",
    "conclusiones": "1",
    "cantidadArticulos": "21",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-006",
    "nombre": "Aromaterapia",
    "otrosNombres": "Terapia con aceites esenciales / masaje con aromaterapia / aromaterapia por inhalación",
    "queEs": "La aromaterapia es el uso de aceites esenciales (principalmente por inhalación o aplicación tópica/masaje) con fines de bienestar o alivio de síntomas. Se usa como terapia complementaria, no sustituta. La evidencia es variable según síntoma y aceite; existen riesgos (dermatitis, intoxicación por ingestión, etc.).",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "930",
    "cantidadRevisiones": "115",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=aromatherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-007",
    "nombre": "Arteterapia",
    "otrosNombres": "Terapia de arte",
    "queEs": "La arteterapia es una forma de intervención en salud mental que utiliza el proceso de creación artística dentro de una relación terapéutica para apoyar bienestar emocional, regulación y comunicación de experiencias difíciles. No requiere “talento” artístico. Se usa como terapia o complemento, dependiendo del caso.",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "729",
    "cantidadRevisiones": "54",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=art+therapy%5BTitle%5D&ac=yes&cauthor_id=None&user_filter=&schema=none&page=1&whatsnew=None&show_snippets=on&sort=relevance&sort_order=desc&format=summary&size=10&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-008",
    "nombre": "Auditación",
    "otrosNombres": "Auditación de Cienciología",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-009",
    "nombre": "Aura Soma",
    "otrosNombres": "Sistema Aura-Soma / Terapia Aura Soma",
    "queEs": "Práctica que utiliza frascos de líquidos de colores, aceites y esencias cuyo fin es equilibrar el \"aura\", las emociones y la energía personal. Se basa en interpretaciones simbólicas del color y en creencias espirituales",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-010",
    "nombre": "Aura",
    "otrosNombres": "Chakras / Terapia de energía / sanación energética / sanación pránica / lectura de aura / Toque terapeutico",
    "queEs": "Conjunto de prácticas que afirman detectar o manipular un “campo energético” humano (aura/biofield) mediante manos cerca del cuerpo o toque ligero (Reiki, Therapeutic Touch, Healing Touch, etc.) para “equilibrar energía” y aliviar síntomas. No existe una medición aceptada del “biofield”; la evidencia clínica es heterogénea y de baja certeza.",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "- hay de \"Migraine aura\" que es algo distinta a terapia de aura",
    "anioReciente": "-"
  },
  {
    "id": "MEV-011",
    "nombre": "Auriculoterapia",
    "otrosNombres": "Terapia auricular / Acupuntura auricular",
    "queEs": "La auriculoterapia es una intervención que estimula puntos del pabellón auricular (con agujas, presión, semillas, electroestimulación, etc.) bajo la idea de que la oreja “representa” al cuerpo. Se usa como terapia complementaria para síntomas como dolor, ansiedad o náusea, con evidencia variable según la condición.",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "187",
    "cantidadRevisiones": "22",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=auriculotherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-012",
    "nombre": "Ayunoterapia",
    "otrosNombres": "Terapia de ayuno / ayuno terapéutico / fasting therapy / fasting cure / fasting detox / ayuno curativo / fasting healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "38",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/37375570/ y otro si buscas \"Fasting intervention\" https://pubmed.ncbi.nlm.nih.gov/32342961/",
    "anioReciente": "2023"
  },
  {
    "id": "MEV-013",
    "nombre": "Balneoterapia",
    "otrosNombres": "Terapia de spa / Terapia termal / Hidroterapia / Crenoterapia",
    "queEs": "La balneoterapia es el uso terapéutico de baños en aguas minerales o termales (a veces con lodos/otros recursos del balneario) como intervención complementaria. Se estudia sobre todo en problemas musculoesqueléticos y algunas dermatosis, con beneficios modestos y evidencia de calidad variable según la indicación.",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "947",
    "cantidadRevisiones": "34",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Balneotherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-014",
    "nombre": "Biocibernética",
    "otrosNombres": "Biocibernética aplicada / biocibernética humana",
    "queEs": "Práctica que propone aplicar conceptos generales de la cibernética y los sistemas de control al funcionamiento del cuerpo humano, con el objetivo de influir en procesos fisiológicos o de salud.",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-015",
    "nombre": "Biomagnetismo",
    "otrosNombres": "Biomagnetismo Médico / Par Biomagnético / Terapia del Par Biomagnético / Terapia con imanes / Imanes terapeuticos / Par Biomagnético de Isaac Goiz / Terapia de pares biomagnéticos / Terapia biomagnética",
    "queEs": "En su uso más común (Goiz), el biomagnetismo aplica pares de imanes estáticos en puntos del cuerpo y afirma “detectar y corregir” alteraciones del pH y problemas asociados a patógenos, usando respuestas corporales (p. ej., acortamiento muscular) para “diagnóstico”. No es equivalente a PEMF médico regulado",
    "riesgos": "",
    "conclusiones": "1",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-016",
    "nombre": "Bioneuroemoción",
    "otrosNombres": "Biodescodificación / Descodificación biológica / Psicobiodescodificación",
    "queEs": "La Bioneuroemoción es una metodología de acompañamiento que propone que conflictos emocionales y patrones inconscientes influyen en síntomas y bienestar. Busca aumentar la autoconciencia y cambiar la interpretación de experiencias vitales. Suele emparentarse con biodescodificación, que asocia enfermedad a conflictos emocionales específicos.",
    "riesgos": "",
    "conclusiones": "0",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-017",
    "nombre": "Biorresonancia",
    "otrosNombres": "",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "14",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-018",
    "nombre": "Biopuntura",
    "otrosNombres": "Terapia de biopuntura / Terapia de inyeccion homeopatica / Mesoterapia homeopática",
    "queEs": "La biopuntura es una técnica de inyección local (subcutánea/intramuscular) en puntos específicos (p. ej., zonas dolorosas, trigger points o seudo-acupuntos) usando preparados “homeopáticos/antihomotóxicos”, a veces mezclados con anestésicos o dextrosa, con el objetivo de reducir dolor e inflamación y “regular” procesos del cuerpo",
    "riesgos": "",
    "conclusiones": "1",
    "cantidadArticulos": "294",
    "cantidadRevisiones": "5",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Mesotherapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "-"
  },
  {
    "id": "MEV-019",
    "nombre": "Bodhi Medicine",
    "otrosNombres": "",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-020",
    "nombre": "Brainspotting",
    "otrosNombres": "Terapia de puntos cerebrales / brainspot therapy / BSP therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "1",
    "cantidadArticulos": "4",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-021",
    "nombre": "Breema",
    "otrosNombres": "Breema bodywork / Breema method / Breema therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-022",
    "nombre": "Brujería",
    "otrosNombres": "Hechicería",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "225",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Witchcraft%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-023",
    "nombre": "Caballoterapia",
    "otrosNombres": "Equinoterapia / terapia asistida con caballos / hipoterapia / equine therapy / equine-assisted therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "215",
    "cantidadRevisiones": "21",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Hippotherapy+%5BTitle%5D&filter=pubt.systematicreview and https://pubmed.ncbi.nlm.nih.gov/?term=Equine-assisted+therapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-024",
    "nombre": "Cafeomancia",
    "otrosNombres": "Tasseomancia / lectura del café / adivinación con café / coffee cup reading / tasseography",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-025",
    "nombre": "Ceremonias holísticas",
    "otrosNombres": "Ritual holístico / ritual espiritual / ceremonia energética / ritual de sanación",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-026",
    "nombre": "Chamanismo",
    "otrosNombres": "Shamanism / prácticas chamánicas / medicina chamánica / curanderismo chamánico",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "83",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-027",
    "nombre": "Cirugía astral",
    "otrosNombres": "Cirugía espiritual / cirugía en el plano astral / psychic surgery",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-028",
    "nombre": "Cirugía energetica",
    "otrosNombres": "Energy surgery / cirugía espiritual energética / healing surgery",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-029",
    "nombre": "Cirugía psíquica",
    "otrosNombres": "Psychic surgery / cirugía espiritual filipina / cirugía psíquica filipina",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-030",
    "nombre": "Coaching transformacional",
    "otrosNombres": "Transformational coaching / coaching de vida profundo / life transformation coaching",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-031",
    "nombre": "Comunicación facilitada",
    "otrosNombres": "Facilitated communication (FC) / supported typing / comunicación asistida",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "89",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/25384895/",
    "anioReciente": "2014"
  },
  {
    "id": "MEV-032",
    "nombre": "Configuración numerológica",
    "otrosNombres": "Numerología terapéutica / terapia numerológica / numerología aplicada / numerological healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-033",
    "nombre": "Control inhibitorio nocivo difuso",
    "otrosNombres": "DNIC (Diffuse Noxious Inhibitory Control) / inhibición nociva difusa / conditioned pain modulation (CPM)",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "21",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-034",
    "nombre": "Constelaciones familiares",
    "otrosNombres": "Terapia sistémica familiar de Bert Hellinger / family constellations",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/33528854/",
    "anioReciente": "2021"
  },
  {
    "id": "MEV-035",
    "nombre": "Constelaciones sistemáticas",
    "otrosNombres": "systemic constellations / constelaciones organizacionales",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-036",
    "nombre": "Cranea-sacral o biodinamica",
    "otrosNombres": "Terapia craneosacral / craniosacral therapy / biodynamic craniosacral therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "60",
    "cantidadRevisiones": "5",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=CranioSacral+Therapy%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2024"
  },
  {
    "id": "MEV-037",
    "nombre": "Cristaloterapia",
    "otrosNombres": "Cristales de Cuarzo / Crystal healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "2",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-038",
    "nombre": "Cromoterapia",
    "otrosNombres": "Terapia de color / Color therapy / color healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "33",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-039",
    "nombre": "Cupping o terapia de las ventosas",
    "otrosNombres": "Ventosaterapia / hijama / suction cup therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "973",
    "cantidadRevisiones": "42",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Cupping+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-040",
    "nombre": "Curación mental",
    "otrosNombres": "Pensamiento curativo /Mental healing / mind healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "14",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-041",
    "nombre": "Curación por la fe",
    "otrosNombres": "Faith healing / sanación espiritual / healing prayer",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "91",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/29696304/",
    "anioReciente": "2018"
  },
  {
    "id": "MEV-042",
    "nombre": "Curanderismo",
    "otrosNombres": "Medicina tradicional mexicana / folk healing / medicina popular",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "20",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-043",
    "nombre": "Descodificación biológica",
    "otrosNombres": "Biodescodificación / biodecoding / decoding therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-044",
    "nombre": "Dharma yoga",
    "otrosNombres": "",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-045",
    "nombre": "Dianética",
    "otrosNombres": "Dianetics therapy / dianetic auditing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-046",
    "nombre": "Diapasones",
    "otrosNombres": "Terapia con diapasones / sound healing with tuning forks / vibrational sound therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "56",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-047",
    "nombre": "Dieta alcalina",
    "otrosNombres": "Alkaline diet / alkaline nutrition / acid-alkaline diet",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "12",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-048",
    "nombre": "Dieta macrobiotica",
    "otrosNombres": "Macrobiotic diet / macrobiotic nutrition",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "22",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-049",
    "nombre": "Digitopuntura / Acupresión",
    "otrosNombres": "Acupresión / acupressure / shiatsu pressure points /shiatsu",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1,245",
    "cantidadRevisiones": "106",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Acupressure+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-050",
    "nombre": "Drenaje linfatico manual",
    "otrosNombres": "Lymphatic drainage massage / manual lymph drainage (MLD)",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "145",
    "cantidadRevisiones": "11",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Manual+Lymphatic+Drainage+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2024"
  },
  {
    "id": "MEV-051",
    "nombre": "Eclecticismo histórico",
    "otrosNombres": "Medicina ecléctica / eclectic medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "70",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-052",
    "nombre": "Ejercicio de respiración",
    "otrosNombres": "Respiración consciente / breathwork / breathing exercises / pranayama",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-053",
    "nombre": "Electroacupuntura",
    "otrosNombres": "Electro-acupuncture / electro stimulation acupuncture",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6,440",
    "cantidadRevisiones": "86",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22electroacupuncture%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-054",
    "nombre": "Electroterapia milagro",
    "otrosNombres": "Electro healing / miracle electrotherapy / bioelectric therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "0",
    "anioReciente": "-"
  },
  {
    "id": "MEV-055",
    "nombre": "EMDR",
    "otrosNombres": "Eye Movement Desensitization and Reprocessing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "448",
    "cantidadRevisiones": "19",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=EMDR+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": ""
  },
  {
    "id": "MEV-056",
    "nombre": "Eneagrama",
    "otrosNombres": "Enneagram personality system / enneagram typing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "13",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/33332604/",
    "anioReciente": "2021"
  },
  {
    "id": "MEV-057",
    "nombre": "Energía contributiva",
    "otrosNombres": "Terapia de energia contributiva / energía vital contributiva / contributive energy healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-058",
    "nombre": "Energía piramidal",
    "otrosNombres": "Pyramid energy / pyramid healing /pyramid power",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-059",
    "nombre": "Enomancia",
    "otrosNombres": "Oenomancy / adivinación con vino / wine divination",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-060",
    "nombre": "Esoterismo",
    "otrosNombres": "Ocultismo / prácticas esotéricas / occultism",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-061",
    "nombre": "Espeleoterapia",
    "otrosNombres": "Cave therapy / salt cave therapy / speleotherapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "41",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Speleotherapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-062",
    "nombre": "Espinología",
    "otrosNombres": "Spinology / spinal energy therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-063",
    "nombre": "Física cuántica",
    "otrosNombres": "Quantum healing / medicina cuántica / quantum medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "21",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-064",
    "nombre": "Farmacoterapia",
    "otrosNombres": "Drug therapy / pharmacologic therapy / medication therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "10,098",
    "cantidadRevisiones": "384",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Pharmacotherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": ""
  },
  {
    "id": "MEV-065",
    "nombre": "Fascioterapia",
    "otrosNombres": "Fasciotherapy / terapia fascial / terapia de fascia",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "14",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/37525195/",
    "anioReciente": "-"
  },
  {
    "id": "MEV-066",
    "nombre": "Feng shui",
    "otrosNombres": "Feng shui clásico / geomancia china / Chinese geomancy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "18",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/37809664/",
    "anioReciente": "2023"
  },
  {
    "id": "MEV-067",
    "nombre": "Fitoterapia",
    "otrosNombres": "Phytotherapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "739",
    "cantidadRevisiones": "27",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Phytotherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-068",
    "nombre": "Fototerapia",
    "otrosNombres": "Terapia de luz / phototherapy / light therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "5,073",
    "cantidadRevisiones": "104",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Phototherapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": ""
  },
  {
    "id": "MEV-069",
    "nombre": "Flores del alba",
    "otrosNombres": "Esencias florales del alba / flower essences of dawn",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-070",
    "nombre": "Frutoterapia",
    "otrosNombres": "Fruit therapy / terapia con frutas",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-071",
    "nombre": "Gemoterapia",
    "otrosNombres": "Cristaloterapia / crystal healing / terapia con gemas",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-072",
    "nombre": "Geobiología",
    "otrosNombres": "Geobiology (esotérica) / geobiología energética",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-073",
    "nombre": "Geometría sagrada",
    "otrosNombres": "Sacred geometry / geometría espiritual",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-074",
    "nombre": "Grafoterapia",
    "otrosNombres": "Graphotherapy / terapia de escritura",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-075",
    "nombre": "Helioterapia",
    "otrosNombres": "Sun therapy / terapia solar / heliotherapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "111",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-076",
    "nombre": "Herbolaria",
    "otrosNombres": "Herbal medicine / botanical medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "88",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22herbalism%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2023"
  },
  {
    "id": "MEV-077",
    "nombre": "Hidroterapia de colon",
    "otrosNombres": "Colon hydrotherapy / colon cleansing / irrigación colónica",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "4",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-078",
    "nombre": "Hipnosis ericksiona",
    "otrosNombres": "Ericksonian hypnosis",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "14",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-079",
    "nombre": "Hipnoterapia",
    "otrosNombres": "Hipnosis / Hypnotherapy / terapia hipnótica",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "5787",
    "cantidadRevisiones": "71",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=hypnotherapy+%5BTitle%5D&filter=pubt.systematicreview and https://pubmed.ncbi.nlm.nih.gov/?term=%22hypnosis%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-080",
    "nombre": "Homeopatía",
    "otrosNombres": "Medicina homeopática / terapia homeopática / remedios homeopáticos / Homeopathy",
    "queEs": "La homeopatía es un sistema alternativo de tratamiento creado a finales del siglo XVIII, basado en la idea de que “lo similar cura lo similar” y en el uso de sustancias altamente diluidas. Sin embargo, las diluciones suelen ser tan extremas que no contienen ninguna molécula activa detectable.",
    "riesgos": "",
    "conclusiones": "Hasta el momento, no hay evidencia científica sólida que respalde el uso de la homeopatía como tratamiento eficaz para ninguna enfermedad.Su uso puede generar una falsa sensación de seguridad y retrasar tratamientos médicos realmente efectivos.",
    "cantidadArticulos": "1,618",
    "cantidadRevisiones": "41",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=homeopathy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2023"
  },
  {
    "id": "MEV-081",
    "nombre": "Homeosynthesis",
    "otrosNombres": "Homeosíntesis / terapia homeosintética",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-082",
    "nombre": "Homotoxicología",
    "otrosNombres": "Homotoxicology / medicina antihomotóxica",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/15197516/",
    "anioReciente": "2004"
  },
  {
    "id": "MEV-083",
    "nombre": "Inducción percutánea de colágeno",
    "otrosNombres": "Microneedling / collagen induction therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "22",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-084",
    "nombre": "Información celular",
    "otrosNombres": "Cell information therapy / cellular information healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-085",
    "nombre": "Iriodología",
    "otrosNombres": "Iriología / análisis del iris",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "21",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=Iridology+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2008"
  },
  {
    "id": "MEV-086",
    "nombre": "Iriogenética",
    "otrosNombres": "Irigenetics / iridogenetics",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-087",
    "nombre": "Johrei",
    "otrosNombres": "",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "17",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-088",
    "nombre": "Kinesiología",
    "otrosNombres": "Kinesiología aplicada / Applied kinesiology / kinesiology therapy / muscle testing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "48",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Applied%20Kinesiology%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-089",
    "nombre": "Lama-fera",
    "otrosNombres": "Lama Fera healing / Lamafera energy healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-090",
    "nombre": "Luminoterapia",
    "otrosNombres": "Light therapy / terapia lumínica",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-091",
    "nombre": "Magia",
    "otrosNombres": "magia ritual / magia popular / magia esotérica",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "5359",
    "cantidadRevisiones": "12",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Magic%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-092",
    "nombre": "Magnetoterapia",
    "otrosNombres": "Magnetic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "170",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-093",
    "nombre": "Masaje Babandi",
    "otrosNombres": "Babandi massage",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-094",
    "nombre": "Masaje Californiano",
    "otrosNombres": "Californian massage",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-095",
    "nombre": "Masaje energético de Chakras",
    "otrosNombres": "Chakra massage / chakra energy massage",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-096",
    "nombre": "Masaje metamórfico",
    "otrosNombres": "Metamorphic technique / metamorphic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-097",
    "nombre": "Masaje Tibetano",
    "otrosNombres": "Tibetan massage",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-098",
    "nombre": "Medicina africana",
    "otrosNombres": "Medicina africana tradicional / Traditional African medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "52",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22African%20Traditional%20medicine%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-099",
    "nombre": "Medicina arábica",
    "otrosNombres": "Arabic traditional medicine / Unani medicine / medicina Unani / Medicina Yunani",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "62",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-100",
    "nombre": "Medicina antroposófica",
    "otrosNombres": "Antroposofía / Anthroposophic medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "58",
    "cantidadRevisiones": "7",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Anthroposophic%20medicine%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D and https://pubmed.ncbi.nlm.nih.gov/?term=%22Anthroposophy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-101",
    "nombre": "Medicina de los mapuches",
    "otrosNombres": "Mapuche traditional medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-102",
    "nombre": "Medicina tradicional del este asiático",
    "otrosNombres": "East Asian traditional medicine / medicina oriental",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "11",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22East%20Asian%20Traditional%20Medicine%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-103",
    "nombre": "Medicina tradicional iraní",
    "otrosNombres": "Persian traditional medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "110",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-104",
    "nombre": "Medicinándolo tradicional Thai",
    "otrosNombres": "Thai traditional medicine / Thai medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "37",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-105",
    "nombre": "Medicina holística",
    "otrosNombres": "Salud holística / Holistic medicine / holistic healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "441",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Holistic%20Health%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-106",
    "nombre": "Medicina cuántica",
    "otrosNombres": "Quantum healing / quantum medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "8",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-107",
    "nombre": "Meditación con números de Grabovoi",
    "otrosNombres": "Grabovoi codes meditation / Grabovoi number therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "",
    "cantidadRevisiones": "",
    "enlacePubMed": "",
    "anioReciente": ""
  },
  {
    "id": "MEV-108",
    "nombre": "Metaloterapia",
    "otrosNombres": "Metal therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "7",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-109",
    "nombre": "Método Kidoc",
    "otrosNombres": "Kidoc method",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-110",
    "nombre": "Método Dorn",
    "otrosNombres": "Dorn therapy / Dorn method",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-111",
    "nombre": "Método Grinberg",
    "otrosNombres": "Grinberg method",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-112",
    "nombre": "Mindfulness",
    "otrosNombres": "Atención plena / mindfulness meditation",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "10,054",
    "cantidadRevisiones": "525",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Mindfulness%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2026"
  },
  {
    "id": "MEV-113",
    "nombre": "Meditación",
    "otrosNombres": "Meditation / contemplative practice",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3,386",
    "cantidadRevisiones": "112",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22meditation%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-114",
    "nombre": "MMS o suplemento mineral milagroso",
    "otrosNombres": "Miracle Mineral Solution / chlorine dioxide therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "2",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-115",
    "nombre": "Moxibuxtión o terapia con artemisa",
    "otrosNombres": "Moxa therapy / moxibustion",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3,035",
    "cantidadRevisiones": "104",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Moxibustion%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2026"
  },
  {
    "id": "MEV-116",
    "nombre": "Musicoterapia",
    "otrosNombres": "Music therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "2,241",
    "cantidadRevisiones": "166",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=music+therapy+%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2026"
  },
  {
    "id": "MEV-117",
    "nombre": "Naturopatía",
    "otrosNombres": "Medicina naturista / Medicina natural / Naturopathy / medicina naturopática",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "594",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-118",
    "nombre": "Neurofeedback",
    "otrosNombres": "EEG biofeedback, neurotherapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "43",
    "cantidadRevisiones": "0",
    "enlacePubMed": "0",
    "anioReciente": ""
  },
  {
    "id": "MEV-119",
    "nombre": "Nueva medicina germánica",
    "otrosNombres": "German New Medicine / Germanic New Medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-120",
    "nombre": "Numerología",
    "otrosNombres": "Numerology / numerological therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "27",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-121",
    "nombre": "Números Grabovoi",
    "otrosNombres": "Códigos Grabovoi / Grabovoi codes / Grabovoi number healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-122",
    "nombre": "Oceanoterapia",
    "otrosNombres": "Terapia marina / marine therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-123",
    "nombre": "Odontología biológica y neurofocal",
    "otrosNombres": "Odontología biológica / odontología neurofocal / biological dentistry / neural therapy dentistry",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "5",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-124",
    "nombre": "Oligoterapia",
    "otrosNombres": "Oligoelementoterapia / terapia con oligoelementos / trace element therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "2",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-125",
    "nombre": "Oncología integrativa",
    "otrosNombres": "Integrative oncology",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "285",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Integrative%20Oncology%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-126",
    "nombre": "Organoterapia",
    "otrosNombres": "Organotherapy / terapia con extractos glandulares",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "50",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-127",
    "nombre": "Orinoterapia",
    "otrosNombres": "Urinoterapia / urine therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "11",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-128",
    "nombre": "Osteopatía",
    "otrosNombres": "Osteopathy / osteopathic medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1149",
    "cantidadRevisiones": "10",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Osteopathy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-129",
    "nombre": "Oxigenación biocatalitica",
    "otrosNombres": "Bio-catalytic oxygen therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-130",
    "nombre": "Ozonoterapia",
    "otrosNombres": "Ozone therapy / oxygen-ozone therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "13",
    "cantidadRevisiones": "30",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22ozone%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-131",
    "nombre": "Péndulo hebreo",
    "otrosNombres": "Hebrew pendulum / terapia del péndulo hebreo",
    "queEs": "utensilio usado en energy healing",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-132",
    "nombre": "Piedras calientes",
    "otrosNombres": "Hot stone massage / masaje con piedras calientes",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-133",
    "nombre": "Pirámide vastu",
    "otrosNombres": "Vastu pyramid therapy / pyramid vastu",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-134",
    "nombre": "Plasma marino",
    "otrosNombres": "Agua de Quinton / Quinton plasma, marine plasma",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-135",
    "nombre": "Proloterapia",
    "otrosNombres": "Proliferation therapy / regenerative injection therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-136",
    "nombre": "Posturología",
    "otrosNombres": "Postural therapy / posturology",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "8",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-137",
    "nombre": "Programación neurolinguistica",
    "otrosNombres": "PNL / NLP (Neuro-Linguistic Programming)",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "67",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Neurolinguistic%20programming%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2012"
  },
  {
    "id": "MEV-138",
    "nombre": "Psicodescodificación",
    "otrosNombres": "Biodescodificación / biodecoding",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-139",
    "nombre": "Psicohomeopatía",
    "otrosNombres": "Psychohomeopathy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-140",
    "nombre": "Psicología Biofeedback",
    "otrosNombres": "Biofeedback therapy / psychophysiological biofeedback",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "19",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-141",
    "nombre": "Psicología cristiana",
    "otrosNombres": "Christian counseling / Christian psychology",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "2",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-142",
    "nombre": "Psicoterapia de imágenes",
    "otrosNombres": "Imagery therapy / guided imagery therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "4",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-143",
    "nombre": "Punción Seca",
    "otrosNombres": "Dry needling",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "826",
    "cantidadRevisiones": "71",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Dry%20Needling%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-144",
    "nombre": "Qigong",
    "otrosNombres": "Chi kung / chi-kung / Qi gong / chi kung / chikung / energía qi exercises",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "716",
    "cantidadRevisiones": "72",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Qigong%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-145",
    "nombre": "Quiropráctica",
    "otrosNombres": "Quiropraxia / Chiropractic / chiropractic therapy / quiropráctico",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3,496",
    "cantidadRevisiones": "44",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22chiropractic%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2024"
  },
  {
    "id": "MEV-146",
    "nombre": "Quinton",
    "otrosNombres": "Plasma de Quinton / agua de mar isotónica / Terapia marina",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "",
    "cantidadRevisiones": "",
    "enlacePubMed": "",
    "anioReciente": ""
  },
  {
    "id": "MEV-147",
    "nombre": "Radioestesia",
    "otrosNombres": "Radiestesia / Dowsing / radiesthesia",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-148",
    "nombre": "Reflexología",
    "otrosNombres": "Reflexology / reflex therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "426",
    "cantidadRevisiones": "29",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Reflexology%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-149",
    "nombre": "Reiki",
    "otrosNombres": "",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "237",
    "cantidadRevisiones": "8",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Reiki%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-150",
    "nombre": "Renacimiento",
    "otrosNombres": "Rebirthing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "7",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-151",
    "nombre": "Risoterapia",
    "otrosNombres": "Laughter therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "52",
    "cantidadRevisiones": "3",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22laughter%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-152",
    "nombre": "Sanación enteogénica",
    "otrosNombres": "Entheogenic healing / psychedelic healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-153",
    "nombre": "Sanación espiritual activa",
    "otrosNombres": "Active spiritual healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "117",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-154",
    "nombre": "Sanación por arquetipos",
    "otrosNombres": "Archetypal healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-155",
    "nombre": "Sanación pránica",
    "otrosNombres": "Pranic healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "9",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-156",
    "nombre": "Semiología",
    "otrosNombres": "Semiotics / clinical semiology",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "805",
    "cantidadRevisiones": "8",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22semiology%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-157",
    "nombre": "Simulación acústica",
    "otrosNombres": "Acoustic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "164",
    "cantidadRevisiones": "3",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Sound%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-158",
    "nombre": "Sofrología",
    "otrosNombres": "Sofronización / Sophrology",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "95",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-159",
    "nombre": "Suero de anguila",
    "otrosNombres": "Eel serum therapy",
    "queEs": "Es una sustancia usada en homeopatía",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "16",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-160",
    "nombre": "Tai chi",
    "otrosNombres": "Tai ji / Tai chi chuan / taiji",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1,845",
    "cantidadRevisiones": "203",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22tai%20chi%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D and https://pubmed.ncbi.nlm.nih.gov/?term=%22tai%20ji%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-161",
    "nombre": "Talasoterapia",
    "otrosNombres": "Thalassotherapy / Terapia marina",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "106",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-162",
    "nombre": "Tantra",
    "otrosNombres": "Tantra yoga / tantra healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "14",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-163",
    "nombre": "Técnica de liberación emocional (EFT)",
    "otrosNombres": "Emotional Freedom Technique / tapping therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "73",
    "cantidadRevisiones": "7",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Emotional%20Freedom%20Techniques%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-164",
    "nombre": "Técnica fosfénica",
    "otrosNombres": "Phosphenic meditation",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-165",
    "nombre": "Técnica metafórmica",
    "otrosNombres": "Metamorphic technique / metamorphic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-166",
    "nombre": "Terapia bioelectromagnética",
    "otrosNombres": "Bioelectromagnetic therapy / electromagnetic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-167",
    "nombre": "Terapia biomagnética",
    "otrosNombres": "Biomagnetism / par biomagnético",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-168",
    "nombre": "Terapia Cognitivo Conductual",
    "otrosNombres": "TCC / CBT / cognitive behavioral therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "5,592",
    "cantidadRevisiones": "311",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Cognitive%20Behavioral%20Therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-169",
    "nombre": "Terapia de drama",
    "otrosNombres": "Drama therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "43",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22dramatherapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D and https://pubmed.ncbi.nlm.nih.gov/?term=%22drama%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-170",
    "nombre": "Terapia de energía",
    "otrosNombres": "Energy therapy / energy healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "40",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Energy%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2021"
  },
  {
    "id": "MEV-171",
    "nombre": "Terapia de baile",
    "otrosNombres": "Dance therapy / dance movement therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "78",
    "cantidadRevisiones": "13",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22dance%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-172",
    "nombre": "Terapia recreativa",
    "otrosNombres": "Terapia de juego / Recreational therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "287",
    "cantidadRevisiones": "3",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22play%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-173",
    "nombre": "Terapia del bosque",
    "otrosNombres": "Shinrin-yoku / forest therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "101",
    "cantidadRevisiones": "11",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22forest%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D and https://pubmed.ncbi.nlm.nih.gov/?term=%22Shinrin-yoku%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-174",
    "nombre": "Terapia de relajación",
    "otrosNombres": "Relaxation therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "216",
    "cantidadRevisiones": "9",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Relaxation%20Therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-175",
    "nombre": "Terapia de renovacion de memoria celular",
    "otrosNombres": "Cellular memory healing",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-176",
    "nombre": "Terapia de tejidos blandos",
    "otrosNombres": "Soft tissue therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "17",
    "cantidadRevisiones": "1",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Soft%20Tissue%20Therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-177",
    "nombre": "Terapia de vidas pasadas",
    "otrosNombres": "Past life regression therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-178",
    "nombre": "Terapia floral (Flores de Bach)",
    "otrosNombres": "Bach flower remedies",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "7",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-179",
    "nombre": "Terapia floral de California",
    "otrosNombres": "California flower essences",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-180",
    "nombre": "Terapia floral de orquídeas",
    "otrosNombres": "Orchid flower essences",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-181",
    "nombre": "Terapia Gerson",
    "otrosNombres": "Dieta Gersón / Gerson therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-182",
    "nombre": "Terapia Gestalt",
    "otrosNombres": "Psicoterapia gestalt / Terapia experencial / Terapia humanista-experiencial / Gestalt therapy",
    "queEs": "La Terapia Gestalt es una psicoterapia humanista y experiencial centrada en el aquí-y-ahora, la toma de conciencia (awareness) y la responsabilidad personal. Trabaja emociones, cuerpo y relación terapéutica para identificar patrones y “asuntos inconclusos”, usando experimentos en sesión (p. ej., silla vacía)",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "49",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-183",
    "nombre": "Terapia hortícola",
    "otrosNombres": "Horticultural therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "83",
    "cantidadRevisiones": "16",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Horticultural%20Therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-184",
    "nombre": "Terapia Humanista",
    "otrosNombres": "Psicoterapia humanista / enfoque humanista / Humanistic therapy",
    "queEs": "La terapia humanista es un enfoque psicoterapéutico que prioriza la experiencia subjetiva, la empatía, la autenticidad y el crecimiento personal. Busca aumentar la conciencia emocional, la autoaceptación y la responsabilidad, centrando la relación terapéutica como principal agente de cambio, más que técnicas estructuradas",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "1",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": ""
  },
  {
    "id": "MEV-185",
    "nombre": "Terapia neural",
    "otrosNombres": "Neural therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "155",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-186",
    "nombre": "Terapia orgónica",
    "otrosNombres": "Orgone therapy / orgone energy therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-187",
    "nombre": "Terapia ortomolecular",
    "otrosNombres": "Orthomolecular medicine",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "4",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-188",
    "nombre": "Terapia psicoanalitica",
    "otrosNombres": "Psicoanalisis / psicotérapia psicodinámica / Psicoterapia de orientacion psicoanalitica / Psychoanalytic therapy",
    "queEs": "La terapia psicoanalítica es un enfoque psicoterapéutico que explora procesos inconscientes, experiencias tempranas y patrones relacionales para comprender el malestar psicológico. Utiliza la relación terapéutica, la asociación libre y la reflexión emocional. Suele ser de larga duración, aunque existen variantes breves psicodinámicas.",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "204",
    "cantidadRevisiones": "2",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Psychoanalytic%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-189",
    "nombre": "Terapia quilante",
    "otrosNombres": "Chelation therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "842",
    "cantidadRevisiones": "17",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Chelation%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-190",
    "nombre": "Terapia radiónica",
    "otrosNombres": "Radionics",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-191",
    "nombre": "Terapia regresiva",
    "otrosNombres": "Regression therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "6",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-192",
    "nombre": "Terapia sistemica",
    "otrosNombres": "Terapia familiar sistémica / terapia de pareja sistemica / Systemic therapy / family systems therapy",
    "queEs": "La psicoterapia sistémica es un enfoque terapéutico que entiende los problemas psicológicos en el contexto de relaciones y patrones (familia, pareja, red social). Interviene sobre comunicación, reglas, roles y dinámicas para reducir síntomas y mejorar funcionamiento. Se aplica en terapia familiar, de pareja y, a veces, individual.",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3,468",
    "cantidadRevisiones": "146",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Systemic%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": ""
  },
  {
    "id": "MEV-193",
    "nombre": "Thetahealing",
    "otrosNombres": "Theta healing meditation",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "0",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  },
  {
    "id": "MEV-194",
    "nombre": "Vacuoterapia",
    "otrosNombres": "Vacuum therapy / vacuum massage",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "413",
    "cantidadRevisiones": "12",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=%22Vacuum%20therapy%22%5BTitle%5D%20AND%20systematic%20review%5BPublication%20Type%5D",
    "anioReciente": "2025"
  },
  {
    "id": "MEV-195",
    "nombre": "Yoga",
    "otrosNombres": "Yoga practice / yogic therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "4,964",
    "cantidadRevisiones": "374",
    "enlacePubMed": "https://pubmed.ncbi.nlm.nih.gov/?term=yoga%5BTitle%5D&filter=pubt.systematicreview",
    "anioReciente": "2026"
  },
  {
    "id": "MEV-196",
    "nombre": "Zerobalancing",
    "otrosNombres": "Zero balancing therapy",
    "queEs": "",
    "riesgos": "",
    "conclusiones": "",
    "cantidadArticulos": "3",
    "cantidadRevisiones": "0",
    "enlacePubMed": "-",
    "anioReciente": "-"
  }
];
